## Imports

In [1]:
import riotwatcher
import time
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('../datasets/match_df.csv')

In [4]:
df.head()

,MATCH_ID,index,companion,gold_left,last_round,level,partner_group_id,placement,players_eliminated,puuid,time_eliminated,total_damage_to_players,traits,units
0,NA1_4176715537,0,{'content_ID': 'b62511df-684d-4ff5-ad59-d3c557...,1,38,8,1.0,4,3,rqonkdDNSZzXwZhDebUd0IgJM2KjjTBp3PKyDKxNfk12KR...,2259.003662,45,"[{'name': 'Set6_Academy', 'num_units': 1, 'sty...","[{'character_id': 'TFT6_Poppy', 'items': [], '..."
1,NA1_4176715537,1,{'content_ID': '390e34e6-4f74-474e-b079-62ba67...,0,38,9,1.0,3,1,s1OlENen9LqyIWheBHoEEe4280YADJzh61sgwO0tGOZLB2...,2253.113281,95,"[{'name': 'Set6_Academy', 'num_units': 2, 'sty...","[{'character_id': 'TFT6_Camille', 'items': [],..."
2,NA1_4176715537,2,{'content_ID': '47f90ee9-181d-4085-a717-f8f5a1...,1,33,7,2.0,8,0,Kd4Xz5DXbrEphO15MDzByPFqYdWVMT_L27vH7Yq6DfDn66...,1946.656860,24,"[{'name': 'Set6_Arcanist', 'num_units': 1, 'st...","[{'character_id': 'TFT6_KogMaw', 'items': [23]..."
3,NA1_4176715537,3,{'content_ID': 'c3edfd17-cb97-49c3-b880-9a38dd...,2,33,9,2.0,7,0,RSs0bQs81xWzeL81iClAevfOirVGPBE4Ctf0lymmscxjSQ...,1954.174438,41,"[{'name': 'Set6_Academy', 'num_units': 2, 'sty...","[{'character_id': 'TFT6_Darius', 'items': [], ..."
4,NA1_4176715537,4,{'content_ID': '969b1b5f-3e5d-44fd-bfa3-1aa798...,2,38,8,3.0,2,3,Wam8F3nXc7JPwe2GAI9lTAUes0y5L5FxoGGDUANg6gdUtr...,2262.025879,95,"[{'name': 'Set6_Arcanist', 'num_units': 2, 'st...","[{'character_id': 'TFT6_Poppy', 'items': [], '..."